name: generate-aath-summary-results
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: read
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: ((success() || failure()) && ((github.event_name != 'pull_request' && github.repository == 'hyperledger/aries-agent-test-harness')))
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v4
        with:
          path: test-harness
      - name: generate-summary-results
        uses: ./test-harness/actions/run-summary-results
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: test-harness
          committer: "Ian Costanzo <ian@anon-solutions.ca>"
          signoff: true
          branch: aath-summary-results
