name: test-harness-acapy-dotnet
on:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness
        uses: ./test-harness/actions/run-test-harness
        with:
          DEFAULT_AGENT: acapy-master
          BOB_AGENT: dotnet-master
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t ~@ProofProposal"
      - name: run-send-gen-test-results
        uses: ./test-harness/actions/run-send-gen-test-results
        with:
          REPORT_PROJECT: acapy-b-dotnet
